steps:
  # Run tests and save to file
  - name: golang:1.20
    entrypoint: /bin/bash
    args: 
      - -c
      - |
        go install github.com/rnicoll/go-ethereum/master@latest
        2>&1 go test -timeout 1m -v ./... | /go/bin/go-junit-report -set-exit-code -iocopy -out ${SHORT_SHA}_test_log.xml
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 
         'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/geth:$SHORT_SHA', '.']
  # Docker push to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/$_REPO_NAME/geth:$SHORT_SHA']
